name: 'Deploy'

on:
  push:
    branches:
      - master

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Sentry Deploys
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_INTEGRATION_TOKEN }}
          SENTRY_ORG: sciolyid
          SENTRY_PROJECT: fossil-id-discord

      - name: Deploy to Dokku
        uses: tctree333/SciOlyID-Actions/deploy-dokku@master
        with:
          dokku app name: fossil-id
          dokku host: ${{ secrets.DOKKU_HOST }}
          ssh private key: ${{ secrets.PRIVATE_KEY }}
